version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prestamos-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3001:3000"  # Puerto 3000 interno mapeado al 3001 externo
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: prestamos-nginx
    restart: always
    ports:
      - "8080:80"  # Cambiado a puerto 8080 para evitar conflictos
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
