version: '3'

services:
  app:
    build: .
    container_name: prestamos-app
    restart: always
    ports:
      - "3001:3000"  # Changed from 3000:3000 to avoid port conflict
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: prestamos-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
