version: '3'

services:
  app:
    build: .
    container_name: prestamos-app
    restart: always
    ports:
      - "3001:3000"  # Puerto 3000 interno mapeado al 3001 externo
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: prestamos-nginx
    restart: always
    ports:
      - "8080:80"  # Cambiado de 80:80 a 8080:80 para evitar conflictos
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
